name: Test

on: [push]

jobs:
  coherence-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install gen.py dependencies
        run: |
          python3 -m pip install regex
      - name: Generating syntax files
        run: |
          make build
      - name: Perform coherence check
        run: |
          sh -s <<EOF
          if [ -n "\$(git status --porcelain)" ]; then
            git diff;
            git status --porcelain=v1 | grep "^.[^M]";
            echo ""
            echo "Generated files above does not match their checked in counterpart.";
            echo "(Make sure to run make build and commit any changes made by that.)";
            exit 1
          fi
          EOF
